version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dj_postgres
    environment:
      POSTGRES_USER: dj_admin
      POSTGRES_PASSWORD: dj_secret_password
      POSTGRES_DB: dj_records
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql # Para scripts automáticos
    networks:
      - dj_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: dj_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dj.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - dj_network
volumes:
  postgres_data:

networks:
  dj_network: